packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@node-rs/argon2": true
  electron: true
  electron-winstaller: false
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - "@linyao.tw/ui@1.4.1"
